[rule]

include = [
  "unused",
  "uninitialized",
  "implicit",
  "duplicate",
  "unreachable",
  "module-name-style",
  "port-name-style",
  "parameter-name-regex",
]


exclude = [
  "copyright",
  "module-filename",
  "nonansi",
  "reg-wire",
  "always-ff",
  "always-comb",
  "always-latch",
  "module-prefix",
  "module-name-regex",
  "port-name-regex",
  "comma-format",
  "unpacked-dimensions-range-ordering",
]

[option.module-name-style]
case = "camel"

[option.port-name-style]
case = "camel"

[option.parameter-name-regex]
regex = "^[A-Z][A-Z0-9_]*$"
